export const seedData = {
  users: {
    _model: "User",
    homer: {
      firstName: "Homer",
      lastName: "Simpson",
      email: "homer@simpson.com",
      password: "secret",
    },
    marge: {
      firstName: "Marge",
      lastName: "Simpson",
      email: "marge@simpson.com",
      password: "secret",
    },
    bart: {
      firstName: "Bart",
      lastName: "Simpson",
      email: "bart@simpson.com",
      password: "secret",
    },
  },
  traillists: {
    _model: "Traillist",
    lenister: {
      name: "Leinster Traillist",
      userid: "->users.bart",
    },
    munster: {
      name: "Munster Traillist",
      userid: "->users.bart",
    },
    ulster: {
      name: "Ulster Traillist",
      userid: "->users.bart",
    },
    connacht: {
      name: "Connacht Traillist",
      userid: "->users.bart",
    },
  },
  trails: {
    _model: "Trail",
    trail_1: {
      name: "Brandon Hill Summit Walk",
      lat: 52.538738,
      lon: -6.96204,
      county: "Kilkenny",
      description: "Hard/Strenuous. Good level of fitness. Forest track and hillside paths and uneven foot",
      traillistid: "->traillists.lenister",
    },
    trail_2: {
      name: "The Barrow Way",
      lat: 52.703418,
      lon: -6.9258294,
      county: "Carlow",
      description: "Vistors can enjoy a excellent flat walking path. The path offers much of architechual interest to the viistor. T",
      traillistid: "->traillists.lenister",
    },
    trail_3: {
      name: "Dublin Mountains Way",
      lat: 53.2220016,
      lon: -6.1558633,
      county: "Dublin",
      description:
        "The entire Dublin Mountain Way is a moderate to strenuous 1 to 3 day (40 km) long distance walking trail close to Dublin City in the Dublin Mountains. This scenic and varied walk is becoming a popular National Waymarked Trail in Ireland and suits walkers from beginners to experienced",
      traillistid: "->traillists.lenister",
    },
    trail_4: {
      name: "Poulanass Waterfall",
      lat: 53.002322,
      lon: -6.345179,
      county: "Wicklow",
      description: "Intermediate Hiking Tour. Good Fitness required. Mostly accessible paths.",
      traillistid: "->traillists.lenister",
    },

    trail_5: {
      name: "Glendalough and the Spinc cliffs",
      lat: 53.022369,
      lon: -6.63856,
      county: "Wicklow",
      description: "Level: Hard, Distance: 8.5 miles, Starts/ends: Glendalough Visitor Centre",
      traillistid: "->traillists.lenister",
    },
    trail_6: {
      name: "Carrauntoohil Hike",
      lat: 51.999456,
      lon: -9.742691,
      county: "Kerry",
      description: "Level: Hard. Level: Hard. Starts/ends: Cronins Yard",
      traillistid: "->traillists.munster",
    },
    trail_7: {
      name: "Clare Coastal Walk Project",
      lat: 53.41291,
      lon: -8.24389,
      county: "Clare",
      description: "Intermediate Hiking Tour. Good Fitness required. Easily accessible paths. Suitable for all skill levels",
      traillistid: "->traillists.munster",
    },
    trail_8: {
      name: "Burren Way",
      lat: 52.721011,
      lon: -9.121311,
      county: "Clare",
      description: "Intermediate Hiking Tour. Good Fitness required. Easily accessible paths. Suitable for all skill levels",
      traillistid: "->traillists.munster",
    },
    trail_9: {
      name: "Ballyhoura Walking Trails",
      lat: 52.275278,
      lon: -8.647778,
      county: "Limerick",
      description: "Intermediate Hiking Tour. Good Fitness required. Easily accessible paths. Suitable for all skill levels",
      traillistid: "->traillists.munster",
    },
    trail_10: {
      name: "Slieve Gullion",
      lat: 54.12183,
      lon: -6.433384,
      county: "Armagh",
      description: "Level: Moderate. Distance: 8 miles. Start/ends: Slieve Gullion Forest Park car park",
      traillistid: "->traillists.ulster",
    },
    trail_11: {
      name: "Cuilcagh Legnabrocky Trail (‘Stairway to Heaven’)",
      lat: 55.245644,
      lon: -7.8117004,
      county: "Fermanagh",
      description: "Level: Easy-moderate. Distance: 4.6 miles. Starts/ends: Cuilcagh Mountain Park car park",
      traillistid: "->traillists.ulster",
    },
    trail_12: {
      name: "Divis and the Black Mountain ridge trail,",
      lat: 54.6112828,
      lon: -6.0184702,
      county: "Belfast",
      description: "Divis and the Black Mountain ridge trail. Distance: 4.2 miles. Starts/ends: National Trust car park at Divis and the Black Mountain",
      traillistid: "->traillists.ulster",
    },
    trail_13: {
      name: "Glenariff Forest Park Scenic Trail",
      lat: 55.013767,
      lon: -6.108022,
      county: "Antrim",
      description: "Level: Moderate. Distance: 6 miles. Starts/ends: Visitors centre at Glenariff Forest Park",
      traillistid: "->traillists.ulster",
    },
    trail_14: {
      name: "Diamond Hill",
      lat: 53.548204,
      lon: -9.914732,
      county: "Galway",
      description: "Diamond Hill, Co Galway, Distance: 4.5 miles, Starts/ends: Connemara National Park Visitor Centre",
      traillistid: "->traillists.connacht",
    },
    trail_15: {
      name: "Achill Island",
      lat: 53.952142,
      lon: -10.009394,
      county: "Mayo",
      description: "Level: Moderate. Distance: 2.8 miles. Starts/ends: The base of Slievemore mountain",
      traillistid: "->traillists.connacht",
    },
  },
};
